# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0248ccd579054774c542dfeb29764c89e3a4c55c72ad8c5102ef9e747d3eb37ea973edf3cc96e7f71100421a20a1b59ac6221a179f94cbbb4c990727ea30ad8e

test:
  secret_key_base: 3eb14b5382e881f89ee02775d5e6c1242d422f0d85ad53d87ce71eaf879c7971944fcbb80fcad5da316e839f1b9572bb843ff04e12ead4a4b403d80e884f2067

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
